components:
  schemas:
    MemUsage200:
      properties:
        code:
          type: string
        message:
          properties:
            active_users:
              format: int32
              type: integer
            after_call_sms_custom:
              format: int32
              type: integer
            after_call_sms_rental:
              format: int32
              type: integer
            call:
              properties:
                leg_b_min:
                  format: int32
                  type: integer
                leg_b_rate:
                  format: int32
                  type: integer
                use:
                  format: int32
                  type: integer
              type: object
            click_o_call_p:
              properties:
                leg_b_min:
                  format: int32
                  type: integer
                leg_b_rate:
                  format: int32
                  type: integer
                use:
                  format: int32
                  type: integer
              type: object
            departments:
              type: string
            extension:
              type: string
            follow_up:
              format: int32
              type: integer
            lines:
              format: int32
              type: integer
            live_calls:
              format: int32
              type: integer
            mobile_recording:
              format: int32
              type: integer
            mobile_sync:
              format: int32
              type: integer
            notification_api:
              format: int32
              type: integer
            notification_email:
              format: int32
              type: integer
            notification_sms:
              format: int32
              type: integer
            obd:
              properties:
                leg_b_min:
                  format: int32
                  type: integer
                leg_b_rate:
                  format: int32
                  type: integer
                use:
                  format: int32
                  type: integer
              type: object
            re-marketing:
              format: int32
              type: integer
            web_call:
              format: int32
              type: integer
            webhook_aftercall:
              format: int32
              type: integer
            webhook_incall:
              format: int32
              type: integer
          type: object
        status:
          type: string
      type: object
    MemcacheAdd200:
      properties:
        message:
          type: string
        result:
          nullable: true
          type: string
        status:
          type: string
      type: object
    MemcacheAdd400:
      properties:
        message:
          type: string
        status:
          type: string
      type: object
    MemcacheConsume200:
      properties:
        code:
          format: int32
          type: integer
        message:
          type: string
        result:
          properties:
            '1':
              format: 'null'
              type: boolean
          type: object
        status:
          type: string
      type: object
    MemcacheConsume200_1:
      properties:
        code:
          format: int32
          type: integer
        message:
          type: string
        result:
          properties:
            1_p_24:
              items:
                oneOf:
                - type: string
              type: array
          type: object
        status:
          type: string
      type: object
    MemcacheDecrement200:
      properties:
        message:
          type: string
        status:
          type: string
      type: object
    MemcacheDelete200:
      properties:
        message:
          format: 'null'
          type: boolean
        status:
          type: string
      type: object
    MemcacheDelete400:
      properties:
        message:
          type: string
        status:
          type: string
      type: object
    MemcacheEngineAdd200:
      properties:
        message:
          type: string
        result:
          nullable: true
          type: string
        status:
          type: string
      type: object
    MemcacheGet200:
      properties:
        result:
          properties:
            1_notification_api:
              properties:
                actual:
                  properties:
                    additional:
                      type: string
                    free:
                      type: string
                  type: object
                display_status:
                  format: int32
                  type: integer
                display_type:
                  type: string
                free:
                  format: int32
                  type: integer
                name:
                  type: string
                service_live_status:
                  type: string
                status:
                  type: string
                unit:
                  type: string
                use:
                  format: int32
                  type: integer
              type: object
          type: object
        status:
          type: string
      type: object
    MemcacheGetOrSet200:
      properties:
        code:
          format: int32
          type: integer
        data:
          properties:
            loginSet_8368782690:
              format: int32
              type: integer
          type: object
        message:
          type: string
        status:
          type: string
      type: object
    MemcacheIncrement200:
      properties:
        message:
          type: string
        status:
          type: string
      type: object
    MemcacheIncrementV1200:
      properties:
        message:
          type: string
        status:
          type: string
      type: object
    MemcacheMultiDelete200:
      properties:
        message:
          format: 'null'
          type: boolean
        status:
          type: string
      type: object
    MemcacheMultiDelete400:
      properties:
        message:
          type: string
        status:
          type: string
      type: object
    MemcacheMultiUpdate200:
      properties:
        code:
          format: int32
          type: integer
        failed_keys:
          items: {}
          type: array
        message:
          type: string
        result:
          items:
            oneOf:
            - type: string
          type: array
        status:
          type: string
      type: object
    MemcacheUpdate200:
      properties:
        message:
          type: string
        result:
          nullable: true
          type: string
        status:
          type: string
      type: object
info:
  description: 'TODO: Add Description'
  title: Memcache
  version: 1.0.0
openapi: 3.0.0
paths:
  /memcache/multi_update:
    post:
      operationId: MemcacheMultiUpdatepost
      parameters:
      - in: header
        name: Content-Type
        schema:
          default: application/x-www-form-urlencoded
          type: string
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              properties:
                data:
                  type: string
              type: object
      responses:
        '200':
          content:
            text/html; charset=UTF-8:
              schema:
                $ref: '#/components/schemas/MemcacheMultiUpdate200'
          description: Memcache Multi Update
  /memcache/get:
    post:
      operationId: MemcacheGetpost
      parameters:
      - in: header
        name: Content-Type
        schema:
          default: application/x-www-form-urlencoded
          type: string
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              properties:
                data:
                  type: string
              type: object
      responses:
        '200':
          content:
            text/html; charset=UTF-8:
              schema:
                $ref: '#/components/schemas/MemcacheGet200'
          description: Get feature
  /memcache/update:
    post:
      operationId: MemcacheUpdatepost
      parameters:
      - in: header
        name: Content-Type
        schema:
          default: application/x-www-form-urlencoded
          type: string
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              properties:
                data:
                  type: string
              type: object
      responses:
        '200':
          content:
            text/html; charset=UTF-8:
              schema:
                $ref: '#/components/schemas/MemcacheUpdate200'
          description: Memcache Multi Update Copy
  /memcache/increment:
    post:
      operationId: MemcacheIncrementpost
      parameters:
      - in: header
        name: Content-Type
        schema:
          default: application/x-www-form-urlencoded
          type: string
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              properties:
                data:
                  type: string
              type: object
      responses:
        '200':
          content:
            text/html; charset=UTF-8:
              schema:
                $ref: '#/components/schemas/MemcacheIncrement200'
          description: Memcache Increment
  /memcache/decrement:
    post:
      operationId: MemcacheDecrementpost
      parameters:
      - in: header
        name: Content-Type
        schema:
          default: application/x-www-form-urlencoded
          type: string
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              properties:
                data:
                  type: string
              type: object
      responses:
        '200':
          content:
            text/html; charset=UTF-8:
              schema:
                $ref: '#/components/schemas/MemcacheDecrement200'
          description: Memcache Decrement
  /memcache/delete:
    post:
      operationId: MemcacheDeletepost
      parameters:
      - in: header
        name: Content-Type
        schema:
          default: application/x-www-form-urlencoded
          type: string
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              properties:
                data:
                  type: string
              type: object
      responses:
        '400':
          content:
            text/html; charset=UTF-8:
              schema:
                $ref: '#/components/schemas/MemcacheDelete400'
          description: Memcache Delete - Unable to delete
        '200':
          content:
            text/html; charset=UTF-8:
              schema:
                $ref: '#/components/schemas/MemcacheDelete200'
          description: Memcache Delete - Success
  /memcache/consume:
    post:
      operationId: MemcacheConsumepost
      parameters:
      - in: header
        name: Content-Type
        schema:
          default: application/x-www-form-urlencoded
          type: string
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              properties:
                data:
                  type: string
              type: object
      responses:
        '200':
          content:
            text/html; charset=UTF-8:
              schema:
                oneOf:
                - $ref: '#/components/schemas/MemcacheConsume200'
                - $ref: '#/components/schemas/MemcacheConsume200_1'
          description: Memcache Consume - Found
  /memcache/engine_add:
    post:
      operationId: MemcacheEngineAddpost
      parameters:
      - in: header
        name: Content-Type
        schema:
          default: application/x-www-form-urlencoded
          type: string
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              properties:
                data:
                  type: string
              type: object
      responses:
        '200':
          content:
            text/html; charset=UTF-8:
              schema:
                $ref: '#/components/schemas/MemcacheEngineAdd200'
          description: Memcache Engine Add
  /memcache/get_or_set:
    post:
      operationId: MemcacheGetOrSetpost
      parameters:
      - in: header
        name: Content-Type
        schema:
          default: application/x-www-form-urlencoded
          type: string
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              properties:
                data:
                  type: string
              type: object
      responses:
        '200':
          content:
            text/html; charset=UTF-8:
              schema:
                $ref: '#/components/schemas/MemcacheGetOrSet200'
          description: Get or Set
  /mem_usage:
    post:
      operationId: MemUsagepost
      parameters:
      - in: header
        name: Content-Type
        schema:
          default: application/x-www-form-urlencoded
          type: string
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              properties:
                data:
                  type: string
              type: object
      responses:
        '200':
          content:
            text/html; charset=UTF-8:
              schema:
                $ref: '#/components/schemas/MemUsage200'
          description: Mem Usage
  /memcache/increment_v1:
    post:
      operationId: MemcacheIncrementV1post
      parameters:
      - in: header
        name: Content-Type
        schema:
          default: application/x-www-form-urlencoded
          type: string
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              properties:
                data:
                  type: string
              type: object
      responses:
        '200':
          content:
            text/html; charset=UTF-8:
              schema:
                $ref: '#/components/schemas/MemcacheIncrementV1200'
          description: Memcache Increment
  /memcache/add:
    post:
      operationId: MemcacheAddpost
      parameters:
      - in: header
        name: Content-Type
        schema:
          default: application/x-www-form-urlencoded
          type: string
      responses:
        '400':
          content:
            text/html:
              schema:
                $ref: '#/components/schemas/MemcacheAdd400'
          description: Memcache Add Invalid Input
        '200':
          content:
            text/html; charset=UTF-8:
              schema:
                $ref: '#/components/schemas/MemcacheAdd200'
          description: Memcache Engine Add
  /memcache/multi_delete:
    post:
      operationId: MemcacheMultiDeletepost
      parameters:
      - in: header
        name: Content-Type
        schema:
          default: application/x-www-form-urlencoded
          type: string
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              properties:
                data:
                  type: string
              type: object
      responses:
        '400':
          content:
            text/html; charset=UTF-8:
              schema:
                $ref: '#/components/schemas/MemcacheMultiDelete400'
          description: Memcache Delete - Unable to delete
        '200':
          content:
            text/html; charset=UTF-8:
              schema:
                $ref: '#/components/schemas/MemcacheMultiDelete200'
          description: Memcache Delete - Success
servers:
- url: http://localhost

